[package]
name = "jukie"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
anyhow = "1.0.86"

# Load config
serde = "1.0.204"
toml = "0.8.15"

# Local music database
sqlx = { version = "0.7", features = [ "sqlite", "runtime-tokio" ] }
audiotags = "0.5.0"
